# Chapter 3 - Basic Math and Statistics

Segment 1 - Using Numpy to perform arithmetic operations on data

In [4]:
import numpy as np
from numpy.random import randn

In [5]:
np.set_printoptions(precision=2)

In [14]:
a = np.array([1,2,3,4,5,6])

In [18]:
b = np.array([[10,20,30], [40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

# Creating arrays
creating arrays using a list

In [6]:
np.random.seed(25)

In [7]:
c = 36*np.random.rand(6)

In [8]:
print(c)

[31.32 20.96 10.04  6.69 14.8   4.23]


In [9]:
c

array([31.32, 20.96, 10.04,  6.69, 14.8 ,  4.23])

In [11]:
d = np.arange(1,35)
c = 36*np.random.randn(6)
c

array([-22.32,  66.16, -73.92,  31.27, -33.15,  -8.36])

In [12]:
d = np.arange(1,35)
d


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [19]:
a * 10


array([10, 20, 30, 40, 50, 60])

In [20]:
c+a

array([-21.32,  68.16, -70.92,  35.27, -28.15,  -2.36])

In [21]:
c-a

array([-23.32,  64.16, -76.92,  27.27, -38.15, -14.36])

In [22]:
c*a

array([ -22.32,  132.33, -221.75,  125.08, -165.73,  -50.18])

In [23]:
c/a

array([-22.32,  33.08, -24.64,   7.82,  -6.63,  -1.39])

# Multiplying matrices and basic linear algebra

In [29]:
aa = np.array([[2.,4. ,6.], [1.,3.,5.], [10.,20.,30.]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [33]:
bb= np.array([[0.,1.,2.], [3.,4.,5.], [6.,7.,8.]])
bb

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
aa**bb

In [34]:
np.dot(aa,bb )

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])

In [36]:
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])